version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
